### ISSUE TITLE
Object reference not set to an instance of an object on updating user settings

### ISSUE THREAD

**Issue by Conleth-XP** [MscrmTools/MsCrmTools.UserSettingsUtility#51]
Error when trying to update a users personalisation settings when using the 
"User Settings Utility"
![image](https://github.com/MscrmTools/MsCrmTools.UserSettingsUtility/assets/157031445/d3307e9d-2a36-4742-90b0-81734b889adc)

This had been mentioned in another article on start-up.
https://github.com/MscrmTools/XrmToolBox/issues/577

Any help is gratefully received

**Comment by MscrmTools** [comment]
Can you indicate what properties you are trying to update and what is the version of your environment?

**Comment by Conleth-XP** [comment]
Hi,
initially I was trying to update the time zone and records per page for a customer.
But now even if I try to update any of the fields e.g. the end time
![image](https://github.com/MscrmTools/MsCrmTools.UserSettingsUtility/assets/157031445/a4f6b191-7440-4d39-8434-7f514205f3a4)

I get the error
Version
![image](https://github.com/MscrmTools/MsCrmTools.UserSettingsUtility/assets/157031445/bf8c7662-5fe1-4089-a2f5-beb5730a0ce2)

thank you

**Comment by skfd** [comment]
Happened to me for `Track email messages` setting too. It also resets the setting I changed when I clock on User in the list. Some state de-sync probably...

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MsCrmTools.UserSettingsUtility.MainControl.tsbUpdateUserSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
